### ISSUE TITLE
Need for git?

### ISSUE THREAD

**Issue by cajomferro** [smarr/ReBench#152]
Whenever I try to execute rebench, it complains it is not a git directory:

```
fatal: No remote configured to list refs from.
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
```

I have tested and it obviously the warning disappears if I am inside a git project. This seems to be a warning but why is it complaining anyway?

**Comment by smarr** [comment]
Hm, yes, this is not great.

The problem is very likely located here:
https://github.com/smarr/ReBench/blob/master/rebench/environment.py#L35-L59

The goal is to obtain information about the sources used for benchmarking and store it in the data file, so that results can more easily be attributed correctly to a specific version/experiment.

Though, yes, this really needs a way to identify if the git access failed, and  also prevent the output.

Since the term just started here, it's unfortunately very unlikely that I get around to looking into it myself any time soon.
Sorry.
