### ISSUE TITLE
`ReBenchLog` gauge adapter doesn't work on case-sensitive filesystems

### ISSUE THREAD

**Issue by raehik** [smarr/ReBench#199]
ReBench's custom benchmark log format is defined in [interop/rebench_log_adapter.py](https://github.com/smarr/ReBench/blob/08c736b78808a67189925fd31484647926341d8c/rebench/interop/rebench_log_adapter.py), in the class `RebenchLogAdapter`. The corresponding `benchmark_suites.${benchmark}.gauge_adapter` value is defined in [executor.py](https://github.com/smarr/ReBench/blob/08c736b78808a67189925fd31484647926341d8c/rebench/executor.py#L449):

https://github.com/smarr/ReBench/blob/08c736b78808a67189925fd31484647926341d8c/rebench/executor.py#L446-L449

So the correct value is `RebenchLog`. However, the documentation and code reference `ReBenchLog` a number of times. On my Linux-based system, that fails to find the gauge adapter. I hazard that it would work on Windows (but probably not MacOS?).

In particular, [`docs/extensions.md`](https://github.com/smarr/ReBench/blob/08c736b78808a67189925fd31484647926341d8c/docs/extensions.md) states the wrong value.

https://github.com/smarr/ReBench/blob/08c736b78808a67189925fd31484647926341d8c/docs/extensions.md#L8-L17

**Comment by raehik** [comment]
Wonder if this can easily be made case-insensitive?

**Comment by smarr** [comment]
My reading of https://python.readthedocs.io/en/latest/library/importlib.html and https://peps.python.org/pep-0235/ is that Python is a case-sensitive language, and I didn't see any option to use case insensitive semantics for the import.

So, I fear that's a documentation bug. 🙁

**Comment by smarr** [comment]
Hm, right. We could intercept well known names, check them case insensitive, and map them to the corresponding and correctly cased name.

Perhaps there's even no need for the dynamic import.
The current model is designed to make it easy to just drop in a suitable file.
But, in practice, none has a custom one.
It's also not really practical since if one would install ReBench via pip, one probably would want to have the gauge adapter somehow separate, possibly next to the benchmark config.

Give that rather suboptimal situation, we could try something like looking for gauge adapters on the disk, and then check case insensitively whether the names match, and use the file name we found on the disk for import.

**Comment by smarr** [comment]
And, yeah, one could possibly indeed drop the dynamic import altogether until someone actually asks for it.

**Comment by raehik** [comment]
It wasn't immediately apparent how to make gauge adapter resolution case insensitive (it's done by attempting to import packages until one hits, not comparing strings/filenames), so I amended some docs and added a more useful error message on failure in #200 .

**Comment by smarr** [comment]
Now implemented as case-insensitive with #202.
